import { useState } from 'react'
import { Download, Zap, Copy, CheckCircle, XCircle, AlertTriangle, FileJson, Layers, Package } from 'lucide-react'
import { parseStatBlock } from './dnd-parser-v20-stable'
import { toFantasyGroundsXML } from './fantasy-grounds-exporter'

// Split input into individual stat blocks on lines containing only "---"
function splitBlocks(text: string): string[] {
  return text
    .split(/^---+\s*$/m)
    .map(b => b.trim())
    .filter(Boolean)
}

type BlockResult = {
  index: number
  name: string
  accuracy: number | null
  defaultedFields: string[]
  errors: string[]
  warnings: string[]
  actor: any
}

export default function BatchProcessor() {
  const [input, setInput]     = useState('')
  const [results, setResults] = useState<BlockResult[]>([])
  const [running, setRunning] = useState(false)
  const [copiedIdx, setCopiedIdx]     = useState<number | null>(null)
  const [copiedFGU, setCopiedFGU]     = useState<number | null>(null)
  const [copiedMacro, setCopiedMacro] = useState(false)

  const runAll = () => {
    setRunning(true)
    setTimeout(() => {
      const blocks = splitBlocks(input)
      const out: BlockResult[] = blocks.map((block, i) => {
        const { errors, warnings, stats, actor } = parseStatBlock(block)
        const name = actor?.name ?? block.split('\n').find(l => l.trim()) ?? `Block ${i + 1}`
        const defaultedFields = (stats?.fields ?? [])
          .filter((f: any) => f.method === 'default')
          .map((f: any) => f.name)
        return {
          index: i,
          name,
          accuracy: stats?.accuracy ?? null,
          defaultedFields,
          errors,
          warnings,
          actor,
        }
      })
      setResults(out)
      setRunning(false)
    }, 50)
  }

  const downloadAll = () => {
    const actors = results.filter(r => r.actor && !r.errors.length).map(r => r.actor)
    if (!actors.length) return
    const blob = new Blob([JSON.stringify(actors, null, 2)], { type: 'application/json' })
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement('a')
    a.href = url
    a.download = 'batch-foundry-import.json'
    a.click()
    URL.revokeObjectURL(url)
  }

  const downloadFGU = () => {
    const actors = results.filter(r => r.actor && !r.errors.length).map(r => r.actor)
    if (!actors.length) return
    // Extract just the <npc>...</npc> body from each single-creature XML,
    // then combine into a npclist module file FGU can import.
    const npcBodies = actors.map((a, i) => {
      const xml  = toFantasyGroundsXML(a)
      const body = xml.match(/<npc>([\s\S]*?)<\/npc>/)?.[1] ?? ''
      const id   = String(i + 1).padStart(5, '0')
      return `\t\t<id-${id}>\n${body}\n\t\t</id-${id}>`
    })
    const xml = [
      `<?xml version="1.0" encoding="utf-8"?>`,
      `<root version="5.1" dataversion="20260124" release="9|CoreRPG:7">`,
      `\t<npclist>`,
      npcBodies.join('\n'),
      `\t</npclist>`,
      `</root>`,
    ].join('\n')
    const blob = new Blob([xml], { type: 'application/xml' })
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement('a')
    a.href = url
    a.download = 'batch-fgu-import.xml'
    a.click()
    URL.revokeObjectURL(url)
  }

  const buildMacroScript = () => {
    const actors = results.filter(r => r.actor && !r.errors.length).map(r => r.actor)
    if (!actors.length) return null
    return [
      `// Batch Actor Import Macro`,
      `// Generated by DnD Stat Block Converter — ${actors.length} actor${actors.length !== 1 ? 's' : ''}`,
      `// Paste into a new Foundry macro and run it.`,
      ``,
      `const actors = ${JSON.stringify(actors, null, 2)};`,
      ``,
      `const created = await Actor.create(actors);`,
      `ui.notifications.info(\`Imported \${created.length} actor\${created.length !== 1 ? 's' : ''} successfully.\`);`,
    ].join('\n')
  }

  const copyMacro = () => {
    const script = buildMacroScript()
    if (!script) return
    navigator.clipboard.writeText(script)
    setCopiedMacro(true)
    setTimeout(() => setCopiedMacro(false), 2000)
  }

  const downloadMacro = () => {
    const script = buildMacroScript()
    if (!script) return
    const blob = new Blob([script], { type: 'text/javascript' })
    const url  = URL.createObjectURL(blob)
    const a    = document.createElement('a')
    a.href = url
    a.download = 'batch-import-macro.js'
    a.click()
    URL.revokeObjectURL(url)
  }

  const copyOne = (r: BlockResult, idx: number) => {
    navigator.clipboard.writeText(JSON.stringify(r.actor, null, 2))
    setCopiedIdx(idx)
    setTimeout(() => setCopiedIdx(null), 1500)
  }

  const copyOneFGU = (r: BlockResult, idx: number) => {
    navigator.clipboard.writeText(toFantasyGroundsXML(r.actor))
    setCopiedFGU(idx)
    setTimeout(() => setCopiedFGU(null), 1500)
  }

  const parsedCount  = results.filter(r => r.actor && !r.errors.length).length
  const successCount = results.filter(r => r.actor && !r.errors.length && !r.defaultedFields?.length && !r.warnings.length).length
  const errorCount   = results.filter(r => r.errors.length > 0).length
  const warnCount    = results.filter(r => !r.errors.length && (r.warnings.length > 0 || r.defaultedFields?.length > 0)).length

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900 p-6">
      <div className="max-w-7xl mx-auto">

        <div className="mb-8 flex items-center gap-3">
          <h1 className="text-4xl font-bold text-white">Batch Processor</h1>
          <span className="bg-blue-600 text-white px-3 py-1 rounded-full text-xs font-bold flex items-center gap-1">
            <Layers size={14} /> Phase 11
          </span>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">

          {/* Left — Input */}
          <div className="space-y-4">
            <div className="bg-slate-800 rounded-lg p-5 border border-purple-500/30">
              <label className="block text-white font-semibold mb-1">Paste Multiple Stat Blocks</label>
              <p className="text-slate-400 text-xs mb-3">Separate each stat block with a line containing only <code className="bg-slate-700 px-1 rounded">---</code></p>
              <textarea
                value={input}
                onChange={e => setInput(e.target.value)}
                placeholder={"Goblin\nSmall humanoid...\n\n---\n\nOrc\nMedium humanoid..."}
                className="w-full h-96 bg-slate-700 text-white rounded p-3 text-sm font-mono border border-purple-400/30 focus:border-purple-400 focus:outline-none resize-none"
              />
              <button
                onClick={runAll}
                disabled={running || !input.trim()}
                className="mt-3 w-full bg-purple-600 hover:bg-purple-700 disabled:opacity-50 text-white font-semibold py-2 px-4 rounded transition flex items-center justify-center gap-2"
              >
                <Zap size={16} />
                {running ? 'Parsing...' : `Parse All Blocks`}
              </button>
            </div>

            {/* Summary bar */}
            {results.length > 0 && (
              <div className="bg-slate-800 rounded-lg p-4 border border-blue-500/30 space-y-3">
                <div className="text-blue-400 font-semibold text-sm">Summary — {results.length} block{results.length !== 1 ? 's' : ''}</div>
                <div className="flex gap-4 text-sm">
                  <span className="text-green-400 flex items-center gap-1"><CheckCircle size={14} /> {successCount} ok</span>
                  <span className="text-yellow-400 flex items-center gap-1"><AlertTriangle size={14} /> {warnCount} warn</span>
                  <span className="text-red-400 flex items-center gap-1"><XCircle size={14} /> {errorCount} failed</span>
                </div>
                <div className="flex gap-2 flex-wrap">
                  <button
                    onClick={copyMacro}
                    disabled={!parsedCount}
                    className="flex items-center gap-1 bg-purple-700 hover:bg-purple-600 disabled:opacity-40 text-white text-xs font-semibold px-3 py-1.5 rounded transition"
                    title="Copy self-contained Foundry macro to clipboard"
                  >
                    {copiedMacro ? <CheckCircle size={13} /> : <Copy size={13} />}
                    {copiedMacro ? 'Copied!' : `Copy Macro (${parsedCount})`}
                  </button>
                  <button
                    onClick={downloadMacro}
                    disabled={!parsedCount}
                    className="flex items-center gap-1 bg-indigo-700 hover:bg-indigo-600 disabled:opacity-40 text-white text-xs font-semibold px-3 py-1.5 rounded transition"
                    title="Download macro as .js file"
                  >
                    <Package size={13} /> Download Macro
                  </button>
                  <button
                    onClick={downloadAll}
                    disabled={!parsedCount}
                    className="flex items-center gap-1 bg-green-700 hover:bg-green-600 disabled:opacity-40 text-white text-xs font-semibold px-3 py-1.5 rounded transition"
                    title="Raw JSON array"
                  >
                    <Download size={13} /> JSON
                  </button>
                  <button
                    onClick={downloadFGU}
                    disabled={!parsedCount}
                    className="flex items-center gap-1 bg-amber-700 hover:bg-amber-600 disabled:opacity-40 text-white text-xs font-semibold px-3 py-1.5 rounded transition"
                  >
                    <Download size={13} /> FGU XML
                  </button>
                </div>
              </div>
            )}
          </div>

          {/* Right — Results */}
          <div className="space-y-3">
            {results.length === 0 && (
              <div className="bg-slate-800 rounded-lg p-8 border border-slate-600/30 text-slate-500 text-center text-sm">
                Results will appear here after parsing.
              </div>
            )}
            {results.map(r => (
              <div
                key={r.index}
                className={`bg-slate-800 rounded-lg p-4 border ${
                  r.errors.length                          ? 'border-red-600/50'
                  : r.warnings.length || r.defaultedFields.length ? 'border-yellow-500/40'
                  : 'border-green-600/40'
                }`}
              >
                {/* Header row */}
                <div className="flex items-center justify-between mb-2">
                  <div className="flex items-center gap-2">
                    {r.errors.length
                      ? <XCircle size={16} className="text-red-400 flex-shrink-0" />
                      : (r.warnings.length || r.defaultedFields.length)
                        ? <AlertTriangle size={16} className="text-yellow-400 flex-shrink-0" />
                        : <CheckCircle size={16} className="text-green-400 flex-shrink-0" />
                    }
                    <span className="text-white font-semibold text-sm">{r.name}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    {r.accuracy !== null && (
                      <span className={`text-xs font-bold px-2 py-0.5 rounded ${
                        r.accuracy >= 80 ? 'bg-green-800 text-green-300'
                        : r.accuracy >= 60 ? 'bg-yellow-800 text-yellow-300'
                        : 'bg-red-800 text-red-300'
                      }`}>{r.accuracy}%</span>
                    )}
                    {r.actor && (
                      <>
                        <button
                          onClick={() => copyOne(r, r.index)}
                          className="flex items-center gap-1 bg-slate-700 hover:bg-slate-600 text-slate-300 text-xs px-2 py-1 rounded transition"
                          title="Copy Foundry JSON"
                        >
                          {copiedIdx === r.index ? <CheckCircle size={12} className="text-green-400" /> : <FileJson size={12} />}
                          {copiedIdx === r.index ? 'Copied' : 'JSON'}
                        </button>
                        <button
                          onClick={() => copyOneFGU(r, r.index)}
                          className="flex items-center gap-1 bg-slate-700 hover:bg-slate-600 text-slate-300 text-xs px-2 py-1 rounded transition"
                          title="Copy FGU XML"
                        >
                          {copiedFGU === r.index ? <CheckCircle size={12} className="text-green-400" /> : <Copy size={12} />}
                          {copiedFGU === r.index ? 'Copied' : 'FGU'}
                        </button>
                      </>
                    )}
                  </div>
                </div>

                {/* Errors */}
                {r.errors.map((e, i) => (
                  <div key={i} className="text-red-300 text-xs bg-red-900/20 rounded px-2 py-1 mt-1">{e}</div>
                ))}

                {/* Warnings */}
                {r.warnings.map((w, i) => (
                  <div key={i} className="text-yellow-300 text-xs bg-yellow-900/20 rounded px-2 py-1 mt-1">{w}</div>
                ))}

                {/* Defaulted fields */}
                {r.defaultedFields.length > 0 && (
                  <div className="text-yellow-400 text-xs bg-yellow-900/20 rounded px-2 py-1 mt-1">
                    Used defaults for: {r.defaultedFields.join(', ')}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  )
}
