// celestial-foundry-export.ts
// Phase 18c — Foundry module generator for the Celestial Calculator
// Downloads a ready-to-install .zip containing module.json, scripts, styles, and template.

import JSZip from 'jszip'
import type { WorldCalendar } from './celestial-data'

// ── Entry point ───────────────────────────────────────────────────────────────
export async function generateFoundryModule(calendar: WorldCalendar): Promise<void> {
  const moduleId = calendar.id.toLowerCase().replace(/[^a-z0-9]+/g, '-') + '-celestial'

  const zip    = new JSZip()
  const folder = zip.folder(moduleId)!

  folder.file('module.json', buildModuleJson(calendar, moduleId))
  folder.file('README.md',   buildReadme(calendar, moduleId))
  folder.folder('scripts')!.file('celestial.js', buildModuleScript(calendar, moduleId))
  folder.folder('styles')!.file('celestial.css', buildModuleCSS())
  folder.folder('templates')!.file('panel.hbs', buildModuleTemplate())

  const blob = await zip.generateAsync({ type: 'blob', compression: 'DEFLATE' })
  const url  = URL.createObjectURL(blob)
  const a    = document.createElement('a')
  a.href     = url
  a.download = moduleId + '.zip'
  a.click()
  URL.revokeObjectURL(url)
}

// ── module.json ───────────────────────────────────────────────────────────────
function buildModuleJson(calendar: WorldCalendar, moduleId: string): string {
  return JSON.stringify({
    id:          moduleId,
    title:       calendar.name + ' — Celestial Calendar',
    description: 'Moon phase tracker and night sky viewer for ' + calendar.name
      + '. Auto-syncs with Simple Calendar. Generated by DnD Parser Toolkit.',
    version:       '1.0.0',
    compatibility: { minimum: '11', verified: '12' },
    authors:       [{ name: 'DnD Parser Toolkit' }],
    scripts:       ['scripts/celestial.js'],
    styles:        ['styles/celestial.css'],
    languages:     [],
    packs:         [],
    relationships: {
      optional: [{
        id:     'foundryvtt-simple-calendar',
        type:   'module',
        reason: 'Enables automatic date sync — without it, set the day manually in module settings.',
      }],
    },
  }, null, 2)
}

// ── README.md ─────────────────────────────────────────────────────────────────
function buildReadme(calendar: WorldCalendar, moduleId: string): string {
  return `# ${calendar.name} — Celestial Calendar

A Foundry VTT module that tracks moon phases, conjunctions, eclipses, and other
celestial events for **${calendar.name}**. Includes an in-game Night Sky panel
that auto-syncs with [Simple Calendar](https://foundryvtt.com/packages/foundryvtt-simple-calendar)
if installed.

Generated by **DnD Parser Toolkit**.

---

## Option A — Manual Install (local game)

1. Extract this \`.zip\` — you'll get a folder named \`${moduleId}\`
2. Copy that folder into your Foundry modules directory:
   - **Windows:** \`%localappdata%\\FoundryVTT\\Data\\modules\\\`
   - **Mac:** \`~/Library/Application Support/FoundryVTT/Data/modules/\`
   - **Linux / self-hosted:** \`~/foundryuserdata/Data/modules/\`
3. In Foundry → **Add-on Modules**, click **Refresh** and enable **${calendar.name} — Celestial Calendar**
4. Click the 🌙 button in the Journal sidebar to open the Night Sky panel

---

## Option B — GitHub-Hosted (share with players / one-click install)

Hosting the module on GitHub lets anyone install it via Foundry's built-in
**Install Module** dialog using a manifest URL — no file extraction needed.

### Steps

1. Create a new GitHub repository (e.g. \`${moduleId}\`)
2. Push the contents of this \`.zip\` so your repo looks like:
   \`\`\`
   ${moduleId}/
   ├── module.json
   ├── README.md
   ├── scripts/
   │   └── celestial.js
   ├── styles/
   │   └── celestial.css
   └── templates/
       └── panel.hbs
   \`\`\`
3. Create a **Release** on GitHub (tag it \`v1.0.0\` to match \`module.json\`)
4. The manifest URL will be:
   \`\`\`
   https://raw.githubusercontent.com/YOUR_USERNAME/${moduleId}/main/${moduleId}/module.json
   \`\`\`
5. In Foundry → **Add-on Modules → Install Module**, paste that URL and click **Install**

### Keeping it up to date

When you regenerate the module (after editing moons or effects), re-download
the \`.zip\`, replace the files in your repo, bump the version in \`module.json\`,
and push a new GitHub Release.

---

## Simple Calendar

Install [Simple Calendar](https://foundryvtt.com/packages/foundryvtt-simple-calendar)
to have the Night Sky panel auto-advance as campaign time passes. Without it,
set **Current Campaign Day** manually in Module Settings.

---

## Moon data

${calendar.moons.map(m => `- **${m.name}** — ${m.orbitDays}-day orbit, ${m.size} (${m.color})`).join('\n')}
`
}

// ── templates/panel.hbs ───────────────────────────────────────────────────────
function buildModuleTemplate(): string {
  return `<div class="cel-panel">

  {{!-- Day navigator --}}
  <div class="cel-nav">
    <button type="button" data-action="nav" data-delta="-7" title="-7 days">−7</button>
    <button type="button" data-action="nav" data-delta="-1" title="Previous day">◀</button>
    <div class="cel-day-display">
      <span class="cel-day-num">Day {{day}}</span>
      <span class="cel-year-num">Year {{year}}</span>
    </div>
    <button type="button" data-action="nav" data-delta="1" title="Next day">▶</button>
    <button type="button" data-action="nav" data-delta="7" title="+7 days">+7</button>
    <button type="button" data-action="reset" title="Return to today">⟳</button>
  </div>

  {{!-- Moon cards --}}
  <div class="cel-moons">
    {{#each moons}}
    <div class="cel-moon-card">
      <div class="cel-moon-icon">{{{svgIcon}}}</div>
      <div class="cel-moon-info">
        <div class="cel-moon-name" style="color: {{color}}">{{name}}</div>
        <div class="cel-moon-phase">{{phaseName}}</div>
        <div class="cel-moon-detail">{{illum}}% lit &middot; {{orbitDays}}d orbit</div>
      </div>
    </div>
    {{/each}}
  </div>

  {{!-- Tonight's events --}}
  {{#if hasEvents}}
  <div class="cel-events">
    <div class="cel-events-header">✦ Tonight's Events</div>
    {{#each events}}
    <div class="cel-event" style="color: {{color}}">{{icon}} {{label}}</div>
    {{/each}}
  </div>
  {{/if}}

  {{!-- Simple Calendar hint --}}
  {{#unless scActive}}
  <div class="cel-sc-hint">Tip: Install Simple Calendar for automatic date sync</div>
  {{/unless}}

</div>`
}

// ── scripts/celestial.js ──────────────────────────────────────────────────────
function buildModuleScript(calendar: WorldCalendar, moduleId: string): string {
  const calJson   = JSON.stringify(calendar, null, 2)
  const worldName = calendar.name

  // NOTE: All JS string building inside uses single-quote concatenation to avoid
  // any backtick/template-literal conflicts with this TypeScript template string.
  return `/* ================================================================
 * ${worldName} — Celestial Calendar Module
 * Generated by DnD Parser Toolkit
 * Install this module in Foundry VTT, then click the moon button
 * in the Journal sidebar to open the Night Sky panel.
 * Optionally install Simple Calendar for automatic date sync.
 * ================================================================ */
(function () {
  'use strict';

  var MODULE_ID = '${moduleId}';
  var CAL = ${calJson};

  // ── Phase math ─────────────────────────────────────────────────────────────
  function moonPhase(moon, day) {
    return (((day / moon.orbitDays) + moon.startPhase) % 1 + 1) % 1;
  }

  function illumination(phase) {
    return 1 - Math.abs(2 * phase - 1);
  }

  function illuminationPct(phase) {
    return Math.round(illumination(phase) * 100);
  }

  function phaseName(phase) {
    var p = ((phase % 1) + 1) % 1;
    if (p < 0.03 || p > 0.97) return 'New Moon';
    if (p < 0.22) return 'Waxing Crescent';
    if (p < 0.28) return 'First Quarter';
    if (p < 0.47) return 'Waxing Gibbous';
    if (p < 0.53) return 'Full Moon';
    if (p < 0.72) return 'Waning Gibbous';
    if (p < 0.78) return 'Last Quarter';
    return 'Waning Crescent';
  }

  // SVG arc path for lit area (centered at origin, radius r)
  function moonPhasePath(r, phase) {
    var p = ((phase % 1) + 1) % 1;
    if (p < 0.01 || p > 0.99) return '';
    if (Math.abs(p - 0.5) < 0.01) {
      return 'M ' + (-r) + ' 0 A ' + r + ' ' + r + ' 0 1 1 ' + r + ' 0 A ' + r + ' ' + r + ' 0 1 1 ' + (-r) + ' 0 Z';
    }
    var waxing     = p < 0.5;
    var ex         = Math.cos(p * 2 * Math.PI) * r;
    var absEx      = Math.abs(ex);
    var outerSweep = waxing ? 1 : 0;
    var innerSweep = waxing ? (ex >= 0 ? 0 : 1) : (ex <= 0 ? 1 : 0);
    if (absEx < 1) {
      return 'M 0 ' + (-r) + ' A ' + r + ' ' + r + ' 0 0 ' + outerSweep + ' 0 ' + r + ' L 0 ' + (-r) + ' Z';
    }
    return 'M 0 ' + (-r) + ' A ' + r + ' ' + r + ' 0 0 ' + outerSweep + ' 0 ' + r
      + ' A ' + absEx + ' ' + r + ' 0 0 ' + innerSweep + ' 0 ' + (-r) + ' Z';
  }

  function moonSVG(moon, day, size) {
    var r    = Math.floor(size / 2) - 3;
    var phase = moonPhase(moon, day);
    var lit  = moonPhasePath(r, phase);
    var cx   = size / 2, cy = size / 2;
    var litPath = lit
      ? '<g transform="translate(' + cx + ',' + cy + ')"><path d="' + lit + '" fill="' + moon.color + '"/></g>'
      : '';
    return '<svg width="' + size + '" height="' + size
      + '" viewBox="0 0 ' + size + ' ' + size + '" xmlns="http://www.w3.org/2000/svg">'
      + '<circle cx="' + cx + '" cy="' + cy + '" r="' + r + '" fill="#060810"/>'
      + litPath
      + '<circle cx="' + cx + '" cy="' + cy + '" r="' + r
        + '" fill="none" stroke="' + moon.color + '" stroke-width="1" opacity="0.4"/>'
      + '</svg>';
  }

  // ── Event detection (today only) ───────────────────────────────────────────
  function phaseDist(a, b) {
    var d = Math.abs(a - b);
    return Math.min(d, 1 - d);
  }

  function phaseSpread(phases) {
    if (phases.length < 2) return 0;
    var max = 0;
    for (var i = 0; i < phases.length; i++) {
      for (var j = i + 1; j < phases.length; j++) {
        max = Math.max(max, phaseDist(phases[i], phases[j]));
      }
    }
    return max;
  }

  function getTodayEvents(day) {
    var moons   = CAL.moons;
    var phases  = moons.map(function (m) { return moonPhase(m, day); });
    var phasesP = moons.map(function (m) { return moonPhase(m, day - 1); });
    var phasesN = moons.map(function (m) { return moonPhase(m, day + 1); });
    var events  = [];

    // Full moons
    moons.forEach(function (moon, i) {
      var ill = illumination(phases[i]);
      if (ill > 0.97 && ill >= illumination(phasesP[i]) && ill >= illumination(phasesN[i])) {
        events.push({ label: moon.name + ' Full Moon', icon: '🌕', color: '#fde68a' });
      }
    });

    // New moons
    moons.forEach(function (moon, i) {
      var d  = Math.min(phases[i], 1 - phases[i]);
      var dP = Math.min(phasesP[i], 1 - phasesP[i]);
      var dN = Math.min(phasesN[i], 1 - phasesN[i]);
      if (d < 0.03 && d <= dP && d <= dN) {
        events.push({ label: moon.name + ' New Moon', icon: '🌑', color: '#94a3b8' });
      }
    });

    if (moons.length >= 2) {
      var spread  = phaseSpread(phases);
      var spreadP = phaseSpread(phasesP);
      var spreadN = phaseSpread(phasesN);
      var isPeak  = spread <= spreadP && spread <= spreadN;

      if (spread < 0.06 && isPeak) {
        var moonNames    = moons.map(function (m) { return m.name; }).join(' & ');
        var allNearFull  = phases.every(function (p) { return illumination(p) > 0.94; });
        if (allNearFull) {
          events.push({ label: 'Lunar Eclipse — ' + moonNames + " pass through " + CAL.name + "'s shadow", icon: '◎', color: '#f87171' });
        } else {
          events.push({ label: moonNames + ' Conjunction', icon: '✦', color: '#c084fc' });
        }
      }

      // Opposition (2-moon worlds)
      if (moons.length === 2) {
        var dist  = phaseDist(phases[0], phases[1]);
        var distP = phaseDist(phasesP[0], phasesP[1]);
        var distN = phaseDist(phasesN[0], phasesN[1]);
        if (dist > 0.47 && dist >= distP && dist >= distN) {
          events.push({ label: moons[0].name + ' & ' + moons[1].name + ' Opposition', icon: '↔', color: '#60a5fa' });
        }
      }
    }

    return events;
  }

  // ── Day helpers ────────────────────────────────────────────────────────────
  function dayToYearDay(day) {
    return ((day - 1) % CAL.daysPerYear) + 1;
  }

  function dayToYear(day) {
    return Math.floor((day - 1) / CAL.daysPerYear) + 1;
  }

  function getCurrentDay() {
    if (typeof SimpleCalendar !== 'undefined' && SimpleCalendar.api) {
      try {
        var dt     = SimpleCalendar.api.currentDateTime();
        var offset = (game.settings.get(MODULE_ID, 'dayOffset') || 0);
        // dayOfTheYear is zero-based in Simple Calendar
        var doy    = dt.dayOfTheYear !== undefined ? dt.dayOfTheYear : (dt.day || 0);
        return Math.max(1, dt.year * CAL.daysPerYear + doy + 1 + offset);
      } catch (e) { /* fall through to manual setting */ }
    }
    return game.settings.get(MODULE_ID, 'currentDay') || 1;
  }

  function setCurrentDay(day) {
    game.settings.set(MODULE_ID, 'currentDay', Math.max(1, day));
  }

  // ── Foundry Application ────────────────────────────────────────────────────
  class CelestialNightSky extends Application {
    constructor() {
      super();
      this._day      = getCurrentDay();
      this._scActive = false;
    }

    static get defaultOptions() {
      return foundry.utils.mergeObject(super.defaultOptions, {
        id:        MODULE_ID + '-panel',
        title:     '✦ ' + CAL.name + ' Night Sky',
        template:  'modules/' + MODULE_ID + '/templates/panel.hbs',
        width:     360,
        height:    'auto',
        resizable: false,
        popOut:    true,
        classes:   ['cel-app'],
      });
    }

    getData() {
      var day   = this._day;
      var moons = CAL.moons.map(function (moon) {
        var phase = moonPhase(moon, day);
        return {
          id:        moon.id,
          name:      moon.name,
          color:     moon.color,
          orbitDays: moon.orbitDays,
          phaseName: phaseName(phase),
          illum:     illuminationPct(phase),
          svgIcon:   moonSVG(moon, day, 54),
        };
      });
      var events = getTodayEvents(day);
      return {
        day:       dayToYearDay(day),
        year:      dayToYear(day),
        moons:     moons,
        events:    events,
        hasEvents: events.length > 0,
        scActive:  this._scActive,
        calName:   CAL.name,
      };
    }

    activateListeners(html) {
      super.activateListeners(html);
      var self = this;
      html.find('[data-action="nav"]').on('click', function () {
        var delta  = parseInt(this.dataset.delta, 10);
        self._day  = Math.max(1, self._day + delta);
        if (!self._scActive) setCurrentDay(self._day);
        self.render(false);
      });
      html.find('[data-action="reset"]').on('click', function () {
        self._day = getCurrentDay();
        self.render(false);
      });
    }

    syncToSC() {
      this._scActive = true;
      this._day      = getCurrentDay();
      if (this.rendered) this.render(false);
    }
  }

  // ── Module lifecycle ───────────────────────────────────────────────────────
  var _panel = null;

  function openPanel() {
    if (!_panel) _panel = new CelestialNightSky();
    if (_panel.rendered) _panel.close();
    else _panel.render(true);
  }

  Hooks.once('init', function () {
    game.settings.register(MODULE_ID, 'currentDay', {
      name:    'Current Campaign Day',
      hint:    'The current day in your campaign. Ignored when Simple Calendar is active.',
      scope:   'world',
      config:  true,
      type:    Number,
      default: 1,
      onChange: function () {
        if (_panel && _panel.rendered) { _panel._day = getCurrentDay(); _panel.render(false); }
      },
    });
    game.settings.register(MODULE_ID, 'dayOffset', {
      name:    'Simple Calendar Day Offset',
      hint:    'Days to add when converting Simple Calendar dates to campaign days.',
      scope:   'world',
      config:  true,
      type:    Number,
      default: 0,
    });
    console.log('${worldName} | Celestial Calendar module initialised.');
  });

  Hooks.once('ready', function () {
    var mod = game.modules.get(MODULE_ID);
    if (mod) mod.api = { openPanel: openPanel, getCurrentDay: getCurrentDay, setCurrentDay: setCurrentDay };

    // Simple Calendar date sync
    Hooks.on('simple-calendar-date-time-change', function () {
      if (_panel) _panel.syncToSC();
    });

    ui.notifications.info('${worldName} Celestial Calendar loaded. Click the moon button in the Journal sidebar.');
  });

  // Journal sidebar button
  Hooks.on('renderJournalDirectory', function (app, html) {
    if (html.find('.cel-journal-btn').length) return;
    var btn = $('<button class="cel-journal-btn" title="${worldName} Night Sky"><i class="fas fa-moon"></i></button>');
    btn.on('click', function (e) { e.preventDefault(); openPanel(); });
    html.find('.directory-header .action-buttons, .directory-header .header-actions').first().append(btn);
  });

})();
`
}

// ── styles/celestial.css ──────────────────────────────────────────────────────
function buildModuleCSS(): string {
  return `/* Celestial Calendar — Generated by DnD Parser Toolkit */

.cel-app .window-content {
  background: #0f172a;
  padding: 0;
  color: #e2e8f0;
  font-family: inherit;
  overflow: hidden;
}

.cel-panel {
  padding: 12px;
  display: flex;
  flex-direction: column;
  gap: 10px;
}

/* ── Navigator ── */
.cel-nav {
  display: flex;
  align-items: center;
  gap: 5px;
  background: #0d1117;
  border: 1px solid #1e293b;
  border-radius: 8px;
  padding: 7px 10px;
}

.cel-nav button {
  background: none;
  border: 1px solid #334155;
  border-radius: 4px;
  color: #94a3b8;
  cursor: pointer;
  padding: 2px 7px;
  font-size: 12px;
  line-height: 1.4;
  transition: all 0.12s;
}

.cel-nav button:hover {
  background: #1e293b;
  color: #e2e8f0;
  border-color: #475569;
}

.cel-day-display {
  flex: 1;
  text-align: center;
}

.cel-day-num {
  color: #e2e8f0;
  font-weight: 700;
  font-size: 15px;
}

.cel-year-num {
  color: #64748b;
  font-size: 13px;
  margin-left: 6px;
}

/* ── Moon cards ── */
.cel-moons {
  display: flex;
  flex-direction: column;
  gap: 7px;
}

.cel-moon-card {
  background: #0d1117;
  border: 1px solid #1e293b;
  border-radius: 8px;
  padding: 9px 12px;
  display: flex;
  align-items: center;
  gap: 12px;
}

.cel-moon-icon svg {
  display: block;
}

.cel-moon-name {
  font-weight: 700;
  font-size: 14px;
  margin-bottom: 2px;
}

.cel-moon-phase {
  color: #94a3b8;
  font-size: 12px;
}

.cel-moon-detail {
  color: #64748b;
  font-size: 11px;
  margin-top: 2px;
}

/* ── Events ── */
.cel-events {
  background: #060912;
  border: 1px solid #7c3aed44;
  border-radius: 8px;
  padding: 9px 12px;
}

.cel-events-header {
  color: #a78bfa;
  font-weight: 600;
  font-size: 11px;
  text-transform: uppercase;
  letter-spacing: 0.06em;
  margin-bottom: 7px;
}

.cel-event {
  font-size: 13px;
  margin-bottom: 3px;
  font-weight: 500;
}

/* ── Footer hint ── */
.cel-sc-hint {
  color: #334155;
  font-size: 10px;
  font-style: italic;
  text-align: center;
  padding: 2px 0 4px;
}

/* ── Journal sidebar button ── */
.cel-journal-btn {
  background: none !important;
  border: 1px solid #334155 !important;
  border-radius: 4px !important;
  color: #94a3b8 !important;
  cursor: pointer;
  padding: 2px 8px !important;
  font-size: 12px !important;
  line-height: 1.5 !important;
  margin-left: 4px;
}

.cel-journal-btn:hover {
  color: #67e8f9 !important;
  border-color: #0e7490 !important;
  background: #0e749015 !important;
}
`
}
