// encounter-builder.tsx — Phase 15b
// Collects parsed creatures into named encounter groups.
// Exports a Foundry VTT macro that creates actors and loads them into the combat tracker.

import { useState } from 'react'
import { Plus, Trash2, Copy, Check, ChevronRight, Swords, X, Edit2, Save } from 'lucide-react'

// ─── TYPES ───────────────────────────────────────────────────

export type EncounterCreature = {
  id: string
  actor: any        // full Foundry actor JSON from parseStatBlock
  quantity: number
}

export type Encounter = {
  id: string
  name: string
  creatures: EncounterCreature[]
}

// ─── HELPERS ─────────────────────────────────────────────────

function uid() {
  return Math.random().toString(36).slice(2, 10)
}

// D&D 5e XP thresholds per character by level [Easy, Medium, Hard, Deadly]
const XP_THRESHOLDS: Record<number, [number, number, number, number]> = {
  1:  [25,   50,   75,   100],  2:  [50,   100,  150,  200],
  3:  [75,   150,  225,  400],  4:  [125,  250,  375,  500],
  5:  [250,  500,  750,  1100], 6:  [300,  600,  900,  1400],
  7:  [350,  750,  1100, 1700], 8:  [450,  900,  1400, 2100],
  9:  [550,  1100, 1600, 2400], 10: [600,  1200, 1900, 2800],
  11: [800,  1600, 2400, 3600], 12: [1000, 2000, 3000, 4500],
  13: [1100, 2200, 3400, 5100], 14: [1250, 2500, 3800, 5700],
  15: [1400, 2800, 4300, 6400], 16: [1600, 3200, 4800, 7200],
  17: [2000, 3900, 5900, 8800], 18: [2100, 4200, 6300, 9500],
  19: [2400, 4900, 7300, 10900],20: [2800, 5700, 8500, 12700],
}

type Difficulty = 'Trivial' | 'Easy' | 'Medium' | 'Hard' | 'Deadly'

function getDifficulty(xp: number, partySize: number, partyLevel: number): { label: Difficulty; color: string } {
  const t = XP_THRESHOLDS[partyLevel] ?? XP_THRESHOLDS[1]
  const [easy, medium, hard, deadly] = t.map(v => v * partySize)
  if (xp === 0)        return { label: 'Trivial', color: '#64748b' }
  if (xp < easy)       return { label: 'Trivial', color: '#64748b' }
  if (xp < medium)     return { label: 'Easy',    color: '#4ade80' }
  if (xp < hard)       return { label: 'Medium',  color: '#fbbf24' }
  if (xp < deadly)     return { label: 'Hard',    color: '#f97316' }
  return               { label: 'Deadly',          color: '#ef4444' }
}

function crLabel(actor: any): string {
  const cr = actor?.system?.details?.cr
  if (cr === undefined || cr === null) return '?'
  if (cr === 0.125) return '1/8'
  if (cr === 0.25)  return '1/4'
  if (cr === 0.5)   return '1/2'
  return String(cr)
}

function totalXP(encounter: Encounter): number {
  const crXpMap: Record<string, number> = {
    '0': 10, '0.125': 25, '0.25': 50, '0.5': 100,
    '1': 200, '2': 450, '3': 700, '4': 1100, '5': 1800,
    '6': 2300, '7': 2900, '8': 3900, '9': 5000, '10': 5900,
    '11': 7200, '12': 8400, '13': 10000, '14': 11500, '15': 13000,
    '16': 15000, '17': 18000, '18': 20000, '19': 22000, '20': 25000,
    '21': 33000, '22': 41000, '23': 50000, '24': 62000, '30': 155000,
  }
  return encounter.creatures.reduce((sum, c) => {
    const cr = c.actor?.system?.details?.cr
    const xp = crXpMap[String(cr)] ?? 0
    return sum + xp * c.quantity
  }, 0)
}

function buildFoundryMacro(encounter: Encounter): string {
  const actorEntries = encounter.creatures.map(c => ({
    actor: c.actor,
    quantity: c.quantity,
  }))

  return [
    `// Encounter: ${encounter.name}`,
    `// ${encounter.creatures.reduce((s, c) => s + c.quantity, 0)} combatants — generated by D&D Parser`,
    ``,
    `(async () => {`,
    `  // Create or find a folder for this encounter's actors`,
    `  let folder = game.folders.find(f => f.name === ${JSON.stringify(encounter.name)} && f.type === 'Actor');`,
    `  if (!folder) folder = await Folder.create({ name: ${JSON.stringify(encounter.name)}, type: 'Actor', color: '#4a1d96' });`,
    ``,
    `  const encounterData = ${JSON.stringify(actorEntries, null, 2)};`,
    ``,
    `  // Get or create a combat encounter`,
    `  let combat = game.combat;`,
    `  if (!combat) combat = await Combat.create({});`,
    ``,
    `  const combatants = [];`,
    `  for (const { actor: raw, quantity } of encounterData) {`,
    `    const { items = [], ...actorData } = raw;`,
    `    let actor = game.actors.getName(actorData.name);`,
    `    if (!actor) {`,
    `      actor = await Actor.create({ ...actorData, items, folder: folder.id });`,
    `    }`,
    `    for (let i = 0; i < quantity; i++) {`,
    `      combatants.push({ actorId: actor.id, hidden: false });`,
    `    }`,
    `  }`,
    ``,
    `  await combat.createEmbeddedDocuments('Combatant', combatants);`,
    `  ui.notifications.info(\`✅ ${encounter.name}: \${combatants.length} combatant\${combatants.length !== 1 ? 's' : ''} added to tracker.\`);`,
    `})();`,
  ].join('\n')
}

// ─── STYLES ──────────────────────────────────────────────────

const S = {
  page:    { minHeight: '100vh', background: '#0f172a', color: '#e2e8f0', fontFamily: 'monospace', display: 'flex' } as const,
  sidebar: { width: 240, minWidth: 240, background: '#1e293b', borderRight: '1px solid #334155', display: 'flex', flexDirection: 'column' as const },
  main:    { flex: 1, padding: 24, overflowY: 'auto' as const },
  muted:   { color: '#64748b', fontSize: 12 } as const,
  tag:     (color: string) => ({ display: 'inline-block', background: color + '22', color, border: `1px solid ${color}55`, borderRadius: 4, padding: '1px 6px', fontSize: 11 }),
  btn:     (color: string, active = true) => ({
    display: 'flex', alignItems: 'center', gap: 6,
    background: active ? color : 'transparent',
    border: `1px solid ${color}`,
    color: active ? '#fff' : color,
    borderRadius: 6, padding: '6px 14px', cursor: 'pointer',
    fontSize: 12, fontWeight: 600, transition: 'all 0.15s',
  }),
}

// ─── CREATURE CARD ────────────────────────────────────────────

function CreatureCard({ creature, onQuantity, onRemove }: {
  creature: EncounterCreature
  onQuantity: (id: string, delta: number) => void
  onRemove: (id: string) => void
}) {
  const a = creature.actor
  const hp  = a?.system?.attributes?.hp?.value ?? '?'
  const ac  = a?.system?.attributes?.ac?.flat ?? '?'
  const cr  = crLabel(a)
  const spd = a?.system?.attributes?.movement?.walk ?? '?'

  return (
    <div style={{ background: '#1e293b', border: '1px solid #334155', borderRadius: 8, padding: '12px 16px', display: 'flex', alignItems: 'center', gap: 12 }}>
      {/* Name + stats */}
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{ color: '#f1f5f9', fontWeight: 700, fontSize: 14, marginBottom: 3, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
          {a?.name ?? 'Unknown'}
        </div>
        <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
          <span style={S.tag('#a78bfa')}>CR {cr}</span>
          <span style={{ ...S.muted }}>HP {hp}</span>
          <span style={{ ...S.muted }}>AC {ac}</span>
          <span style={{ ...S.muted }}>{spd}ft</span>
        </div>
      </div>

      {/* Quantity controls */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 6, flexShrink: 0 }}>
        <button
          onClick={() => onQuantity(creature.id, -1)}
          disabled={creature.quantity <= 1}
          style={{ width: 28, height: 28, borderRadius: 4, border: '1px solid #475569', background: '#0f172a', color: '#94a3b8', cursor: creature.quantity <= 1 ? 'not-allowed' : 'pointer', fontSize: 16, display: 'flex', alignItems: 'center', justifyContent: 'center', opacity: creature.quantity <= 1 ? 0.4 : 1 }}
        >−</button>
        <span style={{ color: '#f1f5f9', fontWeight: 700, fontSize: 15, minWidth: 24, textAlign: 'center' }}>{creature.quantity}</span>
        <button
          onClick={() => onQuantity(creature.id, 1)}
          style={{ width: 28, height: 28, borderRadius: 4, border: '1px solid #475569', background: '#0f172a', color: '#94a3b8', cursor: 'pointer', fontSize: 16, display: 'flex', alignItems: 'center', justifyContent: 'center' }}
        >+</button>
      </div>

      {/* Remove */}
      <button
        onClick={() => onRemove(creature.id)}
        title="Remove from encounter"
        style={{ background: 'none', border: 'none', color: '#475569', cursor: 'pointer', padding: 4, display: 'flex', alignItems: 'center' }}
      >
        <X size={14} />
      </button>
    </div>
  )
}

// ─── MAIN COMPONENT ──────────────────────────────────────────

export default function EncounterBuilder({ encounters, onUpdate }: {
  encounters: Encounter[]
  onUpdate: (encounters: Encounter[]) => void
}) {
  const [activeId, setActiveId]     = useState<string | null>(encounters[0]?.id ?? null)
  const [copied, setCopied]         = useState(false)
  const [editingId, setEditingId]   = useState<string | null>(null)
  const [editName, setEditName]     = useState('')
  const [partySize, setPartySize]   = useState(4)
  const [partyLevel, setPartyLevel] = useState(5)

  const active = encounters.find(e => e.id === activeId) ?? null

  // ── Encounter management ───────────────────────────────────

  const createEncounter = () => {
    const n = encounters.length + 1
    const enc: Encounter = { id: uid(), name: `Encounter ${n}`, creatures: [] }
    const next = [...encounters, enc]
    onUpdate(next)
    setActiveId(enc.id)
  }

  const deleteEncounter = (id: string) => {
    const next = encounters.filter(e => e.id !== id)
    onUpdate(next)
    if (activeId === id) setActiveId(next[0]?.id ?? null)
  }

  const renameEncounter = (id: string, name: string) => {
    onUpdate(encounters.map(e => e.id === id ? { ...e, name } : e))
    setEditingId(null)
  }

  // ── Creature management ────────────────────────────────────

  const adjustQuantity = (creatureId: string, delta: number) => {
    if (!active) return
    onUpdate(encounters.map(e => e.id === active.id ? {
      ...e,
      creatures: e.creatures.map(c =>
        c.id === creatureId ? { ...c, quantity: Math.max(1, c.quantity + delta) } : c
      ),
    } : e))
  }

  const removeCreature = (creatureId: string) => {
    if (!active) return
    onUpdate(encounters.map(e => e.id === active.id ? {
      ...e, creatures: e.creatures.filter(c => c.id !== creatureId),
    } : e))
  }

  const clearEncounter = () => {
    if (!active) return
    onUpdate(encounters.map(e => e.id === active.id ? { ...e, creatures: [] } : e))
  }

  // ── Export ─────────────────────────────────────────────────

  const copyMacro = () => {
    if (!active || !active.creatures.length) return
    const macro = buildFoundryMacro(active)
    if (navigator.clipboard) {
      navigator.clipboard.writeText(macro).catch(() => fallbackCopy(macro))
    } else {
      fallbackCopy(macro)
    }
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const fallbackCopy = (text: string) => {
    const ta = document.createElement('textarea')
    ta.value = text; ta.style.position = 'fixed'; ta.style.opacity = '0'
    document.body.appendChild(ta); ta.focus(); ta.select()
    document.execCommand('copy'); document.body.removeChild(ta)
  }

  // ── XP summary ────────────────────────────────────────────

  const xp = active ? totalXP(active) : 0
  const combatantCount = active?.creatures.reduce((s, c) => s + c.quantity, 0) ?? 0
  const difficulty = active ? getDifficulty(xp, partySize, partyLevel) : null
  const thresholds = XP_THRESHOLDS[partyLevel] ?? XP_THRESHOLDS[1]
  const [easy, medium, hard, deadly] = thresholds.map(v => v * partySize)

  // ─── RENDER ────────────────────────────────────────────────

  return (
    <div style={S.page}>

      {/* Sidebar — encounter list */}
      <div style={S.sidebar}>
        <div style={{ padding: '14px 16px 10px', borderBottom: '1px solid #334155' }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
            <div style={{ color: '#a78bfa', fontWeight: 700, fontSize: 14 }}>Encounters</div>
            <button
              onClick={createEncounter}
              title="New encounter"
              style={{ background: '#7c3aed', border: 'none', borderRadius: 4, color: '#fff', cursor: 'pointer', padding: '3px 7px', fontSize: 18, lineHeight: 1, display: 'flex', alignItems: 'center' }}
            >
              <Plus size={14} />
            </button>
          </div>
        </div>

        <div style={{ flex: 1, overflowY: 'auto' as const, padding: '8px 0' }}>
          {encounters.length === 0 && (
            <div style={{ ...S.muted, padding: '12px 16px', lineHeight: 1.5 }}>
              No encounters yet.<br />Click + to create one.
            </div>
          )}
          {encounters.map(e => (
            <div key={e.id}
              style={{
                display: 'flex', alignItems: 'center', gap: 4,
                padding: '6px 12px',
                background: activeId === e.id ? '#7c3aed22' : 'none',
                borderLeft: `3px solid ${activeId === e.id ? '#7c3aed' : 'transparent'}`,
                cursor: 'pointer',
              }}
              onClick={() => setActiveId(e.id)}
            >
              {editingId === e.id ? (
                <input
                  autoFocus
                  value={editName}
                  onChange={ev => setEditName(ev.target.value)}
                  onBlur={() => renameEncounter(e.id, editName || e.name)}
                  onKeyDown={ev => { if (ev.key === 'Enter') renameEncounter(e.id, editName || e.name) }}
                  onClick={ev => ev.stopPropagation()}
                  style={{ flex: 1, background: '#0f172a', border: '1px solid #7c3aed', borderRadius: 4, color: '#f1f5f9', fontSize: 12, padding: '2px 6px', fontFamily: 'monospace' }}
                />
              ) : (
                <>
                  <ChevronRight size={11} style={{ color: activeId === e.id ? '#a78bfa' : '#475569', flexShrink: 0 }} />
                  <span style={{ flex: 1, color: activeId === e.id ? '#e2e8f0' : '#94a3b8', fontSize: 12, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                    {e.name}
                  </span>
                  <span style={{ ...S.muted, fontSize: 10, flexShrink: 0 }}>{e.creatures.reduce((s, c) => s + c.quantity, 0)}</span>
                </>
              )}

              {/* Edit / delete — only on active, not while editing */}
              {activeId === e.id && editingId !== e.id && (
                <>
                  <button
                    onClick={ev => { ev.stopPropagation(); setEditingId(e.id); setEditName(e.name) }}
                    style={{ background: 'none', border: 'none', color: '#475569', cursor: 'pointer', padding: 2, display: 'flex' }}
                    title="Rename"
                  ><Edit2 size={11} /></button>
                  <button
                    onClick={ev => { ev.stopPropagation(); deleteEncounter(e.id) }}
                    style={{ background: 'none', border: 'none', color: '#475569', cursor: 'pointer', padding: 2, display: 'flex' }}
                    title="Delete encounter"
                  ><Trash2 size={11} /></button>
                </>
              )}
            </div>
          ))}
        </div>

        {/* Sidebar footer hint */}
        <div style={{ padding: '10px 14px', borderTop: '1px solid #334155' }}>
          <div style={{ ...S.muted, fontSize: 11, lineHeight: 1.5 }}>
            Parse a creature in<br />
            <span style={{ color: '#a78bfa' }}>Stat Block Parser</span> →<br />
            click <strong style={{ color: '#e2e8f0' }}>Add to Encounter</strong>
          </div>
        </div>
      </div>

      {/* Main area */}
      <div style={S.main}>
        {!active ? (
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '60vh', gap: 12 }}>
            <Swords size={40} style={{ color: '#334155' }} />
            <div style={{ color: '#475569', fontSize: 14 }}>No encounter selected</div>
            <button onClick={createEncounter} style={{ ...S.btn('#7c3aed'), fontSize: 13 }}>
              <Plus size={14} /> New Encounter
            </button>
          </div>
        ) : (
          <>
            {/* Header */}
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 20, gap: 12 }}>
              <div>
                <div style={{ color: '#f1f5f9', fontWeight: 700, fontSize: 20 }}>{active.name}</div>
                <div style={{ ...S.muted, marginTop: 2 }}>
                  {combatantCount} combatant{combatantCount !== 1 ? 's' : ''} ·{' '}
                  {active.creatures.length} creature type{active.creatures.length !== 1 ? 's' : ''} ·{' '}
                  <span style={{ color: '#fbbf24' }}>{xp.toLocaleString()} XP</span>
                </div>
              </div>

              <div style={{ display: 'flex', gap: 8, flexShrink: 0 }}>
                {active.creatures.length > 0 && (
                  <button onClick={clearEncounter} style={{ ...S.btn('#ef4444', false), fontSize: 12 }}>
                    <Trash2 size={12} /> Clear
                  </button>
                )}
                <button
                  onClick={copyMacro}
                  disabled={!active.creatures.length}
                  style={{
                    ...S.btn(copied ? '#059669' : '#7c3aed'),
                    opacity: active.creatures.length ? 1 : 0.4,
                    cursor: active.creatures.length ? 'pointer' : 'not-allowed',
                  }}
                >
                  {copied ? <Check size={14} /> : <Copy size={14} />}
                  {copied ? 'Copied!' : 'Copy Foundry Macro'}
                </button>
              </div>
            </div>

            {/* Party + Difficulty */}
            <div style={{ background: '#1e293b', border: '1px solid #334155', borderRadius: 8, padding: '14px 16px', marginBottom: 16 }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 20, flexWrap: 'wrap' }}>
                {/* Party inputs */}
                <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                  <span style={{ color: '#94a3b8', fontSize: 12 }}>Party:</span>
                  <input
                    type="number" min={1} max={10} value={partySize}
                    onChange={e => setPartySize(Math.max(1, Math.min(10, +e.target.value)))}
                    style={{ width: 44, background: '#0f172a', border: '1px solid #475569', borderRadius: 4, color: '#f1f5f9', fontSize: 13, padding: '3px 6px', textAlign: 'center', fontFamily: 'monospace' }}
                  />
                  <span style={{ color: '#64748b', fontSize: 12 }}>players</span>
                </div>
                <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                  <span style={{ color: '#94a3b8', fontSize: 12 }}>Level:</span>
                  <input
                    type="number" min={1} max={20} value={partyLevel}
                    onChange={e => setPartyLevel(Math.max(1, Math.min(20, +e.target.value)))}
                    style={{ width: 44, background: '#0f172a', border: '1px solid #475569', borderRadius: 4, color: '#f1f5f9', fontSize: 13, padding: '3px 6px', textAlign: 'center', fontFamily: 'monospace' }}
                  />
                </div>

                {/* Difficulty badge */}
                {difficulty && xp > 0 && (
                  <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginLeft: 'auto' }}>
                    <span style={{ ...S.muted }}>{xp.toLocaleString()} XP</span>
                    <span style={{
                      background: difficulty.color + '22', color: difficulty.color,
                      border: `1px solid ${difficulty.color}55`,
                      borderRadius: 6, padding: '3px 12px', fontSize: 13, fontWeight: 700,
                    }}>{difficulty.label}</span>
                  </div>
                )}
              </div>

              {/* XP threshold bar */}
              {xp > 0 && (() => {
                const max = Math.max(deadly * 1.2, xp * 1.1)
                const pct = (v: number) => `${Math.min(100, (v / max) * 100).toFixed(1)}%`
                return (
                  <div style={{ marginTop: 12 }}>
                    <div style={{ position: 'relative', height: 8, background: '#0f172a', borderRadius: 4, overflow: 'hidden' }}>
                      <div style={{ position: 'absolute', left: 0, top: 0, height: '100%', width: pct(xp), background: difficulty?.color ?? '#7c3aed', borderRadius: 4, transition: 'width 0.3s' }} />
                    </div>
                    <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: 4 }}>
                      {(['Easy', 'Medium', 'Hard', 'Deadly'] as const).map((label, i) => {
                        const val = [easy, medium, hard, deadly][i]
                        const colors = ['#4ade80', '#fbbf24', '#f97316', '#ef4444']
                        return <span key={label} style={{ fontSize: 10, color: colors[i] }}>{label}: {val.toLocaleString()}</span>
                      })}
                    </div>
                  </div>
                )
              })()}
            </div>

            {/* Creature list */}
            {active.creatures.length === 0 ? (
              <div style={{ background: '#1e293b', border: '1px dashed #334155', borderRadius: 8, padding: 40, textAlign: 'center' }}>
                <Swords size={28} style={{ color: '#334155', marginBottom: 10 }} />
                <div style={{ color: '#475569', fontSize: 13, marginBottom: 4 }}>No creatures yet</div>
                <div style={{ ...S.muted }}>
                  Parse a stat block, then click <strong style={{ color: '#a78bfa' }}>Add to Encounter</strong>
                </div>
              </div>
            ) : (
              <div style={{ display: 'flex', flexDirection: 'column', gap: 8, marginBottom: 24 }}>
                {active.creatures.map(c => (
                  <CreatureCard
                    key={c.id}
                    creature={c}
                    onQuantity={adjustQuantity}
                    onRemove={removeCreature}
                  />
                ))}
              </div>
            )}

            {/* Export info */}
            {active.creatures.length > 0 && (
              <div style={{ background: '#1e293b', border: '1px solid #334155', borderRadius: 8, padding: 16 }}>
                <div style={{ color: '#94a3b8', fontSize: 12, fontWeight: 600, marginBottom: 6 }}>About the Macro</div>
                <ul style={{ ...S.muted, margin: 0, paddingLeft: 16, lineHeight: 1.8 }}>
                  <li>Creates a folder named <strong style={{ color: '#e2e8f0' }}>{active.name}</strong> in your Actors directory</li>
                  <li>Creates each actor if not already present (safe to re-run)</li>
                  <li>Adds {combatantCount} combatant{combatantCount !== 1 ? 's' : ''} to the active combat tracker</li>
                  <li>Open or create a combat encounter in Foundry before running</li>
                </ul>
              </div>
            )}
          </>
        )}
      </div>
    </div>
  )
}
